### ISSUE TITLE
lastest node seems to be skipped

### ISSUE THREAD

**Issue by liguyano** [PlayinPistols2d/JsonTreeViewParser#1]
here is my json file ```json [
    {
        "sender": "message_box_1",
        "what": [
            {
                "receiver": "tabview_2",
                "signal": "press lost",
                "slot": []
            },
            {
                "receiver": "tabview_2",
                "signal": "press lost",
                "slot": [
                    {
                        "para": [
                            "Focus Key"
                        ],
                        "recvevent": "addState"
                    },
                    {
                        "para": [
                            13
                        ],
                        "recvevent": "BorderWidth"
                    }
                ]
            },
            {
                "receiver": "label_3",
                "signal": "press lost",
                "slot": [
                    {
                        "para": [
                            14
                        ],
                        "recvevent": "BorderWidth"
                    },
                    {
                        "para": [
                            22
                        ],
                        "recvevent": "Radius"
                    }
                ]
            }
        ]
    },
    {
        "sender": "tabview_1",
        "what": [
            {
                "receiver": "text_area_1",
                "signal": "press lost",
                "slot": [
                    {
                        "para": [
                            11
                        ],
                        "recvevent": "setWidth"
                    },
                    {
                        "para": [
                            18
                        ],
                        "recvevent": "setHeight"
                    },
                    {
                        "para": [
                            "#55ff7f"
                        ],
                        "recvevent": "BorderColor"
                    }
                ]
            },
            {
                "receiver": "label_3",
                "signal": "press lost",
                "slot": [
                    {
                        "para": [
                            13
                        ],
                        "recvevent": "setHeight"
                    },
                    {
                        "para": [
                            16,
                            18
                        ],
                        "recvevent": "position"
                    },
                    {
                        "para": [
                            99
                        ],
                        "recvevent": "BorderOpa"
                    }
                ]
            }
        ]
    }
] ```

**Comment by PlayinPistols2d** [comment]
Hello @liguyano,

Thanks for the info!

I quickly ran your example while at work, and it seems that the actual nodes are shown correctly for your example. However, the code doesn’t handle displaying the actual values of those nodes.

I’ll investigate that as soon as I have some spare time, and I’ll also fix the array issue mentioned in the ToDo section. Once again, thank you for the bump. Feel free to collaborate if you’d like!

**Comment by liguyano** [comment]
thank you for you replay ,
yes I mean that the  value not visible .
I would be very grateful if you add this funcion

**Comment by PlayinPistols2d** [comment]
@liguyano, ah and one more thing, if you need such functionality as soon as possible, you can check this great project out
https://github.com/dridk/QJsonModel

**Comment by PlayinPistols2d** [comment]
Greetings @liguyano,

I'm happy to inform you that I've patched the class. It should now work as intended. Please check it out.
e73b5e1f51207162d0442b0fb2475daccc3c358c

**Comment by liguyano** [comment]
it worked！ thank you so much for add this function, this really help a lot.
